
image: docker:19.03.1
services:
    - docker:19.03.1-dind

stages:
    - build
    - publish

before_script:
    - echo "${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}" > VERSION
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:latest:
    stage: build
    except:
        - tags
    script:
        - docker build -t ${CI_REGISTRY_IMAGE}:latest .
        - docker save ${CI_REGISTRY_IMAGE}:latest > build_latest.img
    artifacts:
        paths:
            - build_latest.img
        expire_in: 1 week

publish:latest:
    stage: publish
    except:
        - tags
    script:
        - docker load < build_latest.img
        - docker push ${CI_REGISTRY_IMAGE}:latest
    dependencies:
        - build:latest

build:tag:
    stage: build
    only:
        - tags
    script:
        - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
        - docker save ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} > build_${CI_COMMIT_TAG}.img
    artifacts:
        paths:
            - build_${CI_COMMIT_TAG}.img
        expire_in: 1 week

publish:tag:
    stage: publish
    only:
        - tags
    script:
        - docker load < build_${CI_COMMIT_TAG}.img
        - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    dependencies:
        - build:tag

